### ISSUE TITLE
django.template.exceptions.TemplateSyntaxError

### ISSUE THREAD

**Issue by TRSWNCA** [Ibercivis/EU-CS_platform#663]
Hi guys!

When I run `python manage migrate.py`, error occurs:

```
System check identified no issues (0 silenced).
December 13, 2021 - 05:28:45
Django version 2.2.24, using settings 'eucs_platform.settings.development'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d1a80>
==========
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d1c40>
==========
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d1e00>
==========
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d1fc0>
==========
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d4180>
==========
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d4340>
==========
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d4500>
==========
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d46c0>
==========
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d4880>
==========
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d4a40>
==========
==========
<WSGIRequest: GET '/'> <class 'django.template.exceptions.TemplateSyntaxError'> 'block' tag with name 'head' appears more than once <traceback object at 0x7f774d9d4c00>
==========
Traceback (most recent call last):
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/wsgi.py", line 32, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tank/Desktop/EU-CS_platform/src/eucs_platform/views.py", line 105, in home
    return render(request, 'home.html', {
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/tank/Desktop/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 205, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'head' appears more than once
```

It seems that the template of '/' is wrong. Is there any solution? thx.

I use Ubuntu 20.04 and branch master by the way.

**Comment by frasanz** [comment]
There was some errors in master branch, platform_beta was the one working. Now, master is the default-working branch. Hope this solve the bug
